# This is the master compose file that includes all the other ones.
version: "3"

volumes:
  pgdata:

services:
  nginx:
    restart: always
    image: nginx:1.15-alpine
    volumes:
      - static_me:/app/me/staticfiles
      - static_spotifly:/app/spotfily/staticfiles
      - ./config/etc/letsencrypt:/etc/letsencrypt
      - ./nginx:/etc/nginx/conf.d # this is how we use custom nginx build
    ports:
      - "80:80"
      - "443:443"
  postgres:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env