# this container automates the process of generating wildcard certificates
version: '3'
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - URL=thatcherthornberry.com
      - SUBDOMAINS=auxocracy,
      - VALIDATION=dns
      - DNSPLUGIN=google
      - EMAIL=thatcherthornberry@gmail.com
      - DHLEVEL=4096
    volumes:
      - /home/sa_109683913549673363733/config:/config
    restart: unless-stopped