# This is the master compose file that includes all the other ones.
version: "3"

volumes:
  pgdata:

services:
  nginx:
    restart: always
    image: nginx:1.15-alpine
    depends_on:
      - web
    volumes:
      - ./projects/me/staticfiles:/home/app/web/staticfiles
      - ./projects/spotifly/staticfiles:/home/app/staticfiles
      - ./config/etc/letsencrypt:/etc/letsencrypt
      - ./data/nginx:/etc/nginx/conf.d # this is how we use custom nginx build
    ports:
      - "80:80"
      - "443:443"
  postgres:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
  spotiflyweb:
    restart: always
    build: ./projects/spotifly
    image: thatcherthornberry/spotifly:latest
    command: gunicorn music.wsgi:application --bind 0.0.0.0:8001 && python manage.py migrate
    expose:
      - "8001"
    env_file:
      - ./projects/spotifly/.env
    depends_on:
      - postgres
  web:
    restart: always
    build: ./projects/me
    image: thatcherthornberry
    command: gunicorn thatcherthornberry.wsgi:application -b 0.0.0.0:8000 && python manage.py migrate
    expose:
      - "8000"
    env_file:
      - ./projects/me/.env
    depends_on:
      - postgres