# TODO: revisit and test
version: "3"

volumes:
  pgdata:


services:
  # TODO: figure out local implementation
  nginx:
    restart: always
    image: nginx:1.15-alpine
    depends_on:
      - me
    volumes:
      - ./nginx:/etc/nginx/conf.d # this is how we use custom nginx build

    ports:
      - "80:80"
  postgres:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
  me:
    restart: always
    build: .
    image: thatcherthornberry
    command: bash -c " python manage.py migrate && gunicorn thatcherthornberry.wsgi:application -b 0.0.0.0:8000"
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    environment:
      - DOCKER_LOCAL=True
    depends_on:
      - postgres

# TODO: revisit networks
# networks:
#   default:
#     name: thatcherthornberry
