version: "3"

volumes:
  pgdata:
  redisdata:
  static_spotfily:


services:
  nginx:
    restart: always
    image: nginx:1.15-alpine
    depends_on:
      - me
    volumes:
      - ./nginx:/etc/nginx/conf.d # this is how we use custom nginx build
      - static_spotifly:/app/spotifly/staticfiles
    ports:
      - "80:80"

  spotifly:
  # TODO: probably need some volumes to port code while developing.. bong
    restart: always
    build: .
    image: thatcherthornberry/spotifly:latest
    command: bash -c "python manage.py migrate && gunicorn thatcherthornberry.wsgi:application -b 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - static_spotifly:/app/spotifly/staticfiles
    env_file:
      - .env
    environment:
      - DOCKER_LOCAL=True
    depends_on:
      - postgres
  postgres:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
  redis:
    restart: always
    image: redis:6
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redisdata:/data
  # TODO: refactor these to their own repo or something
  scheduler:
    restart: always
    image: thatcherthornberry/spotifly:latest
    command: python manage.py rqscheduler --queue default
    env_file:
      - .env
    environment:
      - DOCKER_LOCAL=True
    depends_on:
      - "redis"

  # TODO: refactor these to their own repo or something
  worker:
    restart: always
    image: thatcherthornberry/spotifly:latest
    command: python manage.py rqworker default
    env_file:
      - .env
    environment:
      - DOCKER_LOCAL=True
    depends_on:
      - "redis"
