version: "3"

volumes:
  pgdata:
  redisdata:

services:
  spotifly:
    restart: always
    build: .
    image: thatcherthornberry/spotifly:latest
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app/spotifly
    env_file:
      - .env
    environment:
      - SPOTIFY_REDIRECT_URI=http://0.0.0.0:8000/redirect
    depends_on:
      - postgres
  postgres:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
  redis:
    restart: always
    image: redis:6
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
  # TODO: refactor these to their own repo or something
  scheduler:
    restart: always
    image: thatcherthornberry/spotifly:latest
    command: python manage.py rqscheduler --queue default
    env_file:
      - .env
    depends_on:
      - "redis"

  # TODO: refactor these to their own repo or something
  worker:
    restart: always
    image: thatcherthornberry/spotifly:latest
    command: python manage.py rqworker default
    env_file:
      - .env
    depends_on:
      - "redis"
