services:
  blog:
    build: .
    command: bash -c " python manage.py migrate && python manage.py collectstatic
      --noinput && gunicorn blog.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
    - .env
    expose:
    - 8001
    image: blog:latest
    restart: always
    volumes:
    - static_blog:/app/blog/staticfiles
  nginx:
    image: nginx:1.15-alpine
    ports:
    - 80:80
    - 443:443
    restart: always
    volumes:
    - static_blog:/app/blog/staticfiles
    - ./nginx:/etc/nginx/conf.d
  postgres:
    env_file:
    - .env
    healthcheck:
      interval: 5s
      retries: 5
      test:
      - CMD-SHELL
      - pg_isready -U $POSTGRES_DB
      timeout: 5s
    image: postgres:12.0-alpine
    ports:
    - 5432:5432
    restart: always
    volumes:
    - pgdata:/var/lib/postgresql/data
  redis:
    command: --requirepass ${REDIS_PASSWORD}
    env_file: .env
    image: redis:6
    ports:
    - 6379:6379
    restart: always
    volumes:
    - redisdata:/data
version: '3'
volumes:
  pgdata: null
  redisdata: null
  static_blog: null
