# Generated by Django 3.2.5 on 2021-07-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queueing", "0004_alter_follower_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="listener",
            name="spotify_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
