# Generated by Django 3.2.5 on 2021-07-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("queueing", "0008_auto_20210728_0425"),
    ]

    operations = [
        migrations.RemoveField(model_name="listener", name="number",),
    ]
