# Generated by Django 2.2 on 2021-09-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queueing", "0016_auto_20210830_2223"),
    ]

    operations = [
        migrations.AddField(
            model_name="listener",
            name="max_offset",
            field=models.IntegerField(default=5000),
        ),
    ]
