# Generated by Django 3.2.5 on 2021-07-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queueing", "0006_auto_20210728_0348"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follower",
            name="following",
            field=models.CharField(default="thatcher", max_length=100),
            preserve_default=False,
        ),
    ]
