# Generated by Django 3.2.5 on 2021-08-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queueing", "0013_listener_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="listener",
            name="expires_in",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listener",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
