# Generated by Django 4.1.2 on 2022-10-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queueing", "0019_delete_follower"),
    ]

    operations = [
        migrations.AddField(
            model_name="listener",
            name="anon",
            field=models.BooleanField(default=False),
        ),
    ]
