name: Deploy to thatcherthornberry on GCE

on:
  repository_dispatch:
    types: [pull-trigger]

env:
  PROJECT: ${{ github.event.client_payload.project }}
  REPO: ${{ github.event.client_payload.repo }}

jobs:
  Pull-Code:
    name: Pull Code For Subtree
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: setup git config
        run: |  
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git config github.token ${{ secrets.PAT_TOKEN}}

      - name: Pull and Push
        run: |
          # pull the subtree, push those changes to the repo
          git subtree pull --prefix=projects/$PROJECT $REPO master --squash
          git push origin master
