name: Pull Code on Trigger

on:
  repository_dispatch:
    types: [pull-trigger]

env:
  PROJECT: ${{ github.event.client_payload.project }}
  REPO: ${{ github.event.client_payload.repo }}

jobs:
  Pull-Code:
    name: Pull Code For Subtree
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - name: see whats up
        run: ls -la
      - name: Pull and Push
        run: |
          # pull the subtree, push those changes to the repo
          git subtree add --prefix projects/$PROJECT https://thatcherT:${{ secrets.PAT_TOKEN }}$REPO master --squash
          git subtree pull --prefix=projects/$PROJECT https://ThatcherT:${{ secrets.PAT_TOKEN }}$REPO master --squash -m "trigger update"
          git push origin master
