name: Deploy to thatcherthornberry on GCE

on:
  repository_dispatch:
    types: [pull-trigger]

jobs:
  Pull-Code:
    name: Pull Code For Subtree
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - env:
          PROJECT: ${{ github.event.client_payload.project }}
          REPO: ${{ github.event.client_payload.repo }}
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: setup git config
        run: |  
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Pull and Push
        run: |
          # pull the subtree, push those changes to the repo
          git subtree pull --prefix=projects/$PROJECT $REPO master --squash
          git push origin master
